---
abstract: 'A perl implementation of JavaScript''s escape() and unescape() functions'
author:
  - 'Koichi Taniguchi <taniguchi@livedoor.jp>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.94'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-Escape-JavaScript
no_index:
  directory:
    - inc
    - t
requires:
  Encode: 2.12
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
