abstract: A perl implementation of JavaScript's escape() and unescape() functions
author: Koichi Taniguchi <taniguchi@livedoor.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: URI-Escape-JavaScript
no_index: 
  directory: 
    - inc
    - t
requires: 
  Encode: 2.12
  perl: 5.8.1
version: 0.02
